using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace IEvangelist.GitHub.Services.Filters
{
    static class InappropriateLanguage
    {
        #region Borrowed from several locations:

        // https://raw.githubusercontent.com/web-mech/badwords/master/lib/lang.json
        // https://www.freewebheaders.com/full-list-of-bad-words-banned-by-google/

        static string[] WordsAndPhrases { get; } = new[]
        {
            "$h!t",
            "*damn",
            "*dyke",
            "*fuck*",
            "*shit*",
            "@$$",
            "2 girls 1 cup",
            "2g1c",
            "4r5e",
            "5h1t",
            "5hit",
            "a$$",
            "a$$hole",
            "a_s_s",
            "a2m",
            "a54",
            "a55",
            "a55hole",
            "acrotomophilia",
            "aeolus",
            "ahole",
            "alabama hot pocket",
            "alaskan pipeline",
            "amcik",
            "anal",
            "anal impaler",
            "anal leakage",
            "analprobe",
            "andskota",
            "anilingus",
            "anus",
            "apeshit",
            "ar5e",
            "areola",
            "areole",
            "arian",
            "arrse",
            "arschloch",
            "arse",
            "arse*",
            "arsehole",
            "aryan",
            "ash0le",
            "ash0les",
            "asholes",
            "ass",
            "ass fuck",
            "ass hole",
            "Ass Monkey",
            "assbag",
            "assbandit",
            "assbang",
            "assbanged",
            "assbanger",
            "assbangs",
            "assbite",
            "assclown",
            "asscock",
            "asscracker",
            "asses",
            "assface",
            "assfaces",
            "assfuck",
            "assfucker",
            "ass-fucker",
            "assfukka",
            "assgoblin",
            "assh0le",
            "assh0lez",
            "asshat",
            "ass-hat",
            "asshead",
            "assho1e",
            "asshole",
            "assholes",
            "assholz",
            "asshopper",
            "ass-jabber",
            "assjacker",
            "asslick",
            "asslicker",
            "assmaster",
            "assmonkey",
            "assmucus",
            "assmunch",
            "assmuncher",
            "assnigger",
            "asspirate",
            "ass-pirate",
            "assrammer",
            "assshit",
            "assshole",
            "asssucker",
            "asswad",
            "asswhole",
            "asswipe",
            "asswipes",
            "auto erotic",
            "autoerotic",
            "axwound",
            "ayir",
            "azazel",
            "azz",
            "azzhole",
            "b!+ch",
            "b!tch",
            "b00b*",
            "b00bs",
            "b17ch",
            "b1tch",
            "babeland",
            "baby batter",
            "baby juice",
            "ball gag",
            "ball gravy",
            "ball kicking",
            "ball licking",
            "ball sack",
            "ball sucking",
            "ballbag",
            "balls",
            "ballsack",
            "bampot",
            "bang (one's) box",
            "bangbros",
            "bareback",
            "barely legal",
            "barenaked",
            "barf",
            "bassterds",
            "bastard",
            "bastardo",
            "bastards",
            "bastardz",
            "basterds",
            "basterdz",
            "bastinado",
            "batty boy",
            "bawdy",
            "bbw",
            "bdsm",
            "beaner",
            "beaners",
            "beardedclam",
            "beastial",
            "beastiality",
            "beatch",
            "beaver",
            "beaver cleaver",
            "beaver lips",
            "beef curtain",
            "beef curtains",
            "beeyotch",
            "bellend",
            "bender",
            "beotch",
            "bescumber",
            "bestial",
            "bestiality",
            "bi+ch",
            "bi7ch",
            "Biatch",
            "big black",
            "big breasts",
            "big knockers",
            "big tits",
            "bigtits",
            "bimbo",
            "bimbos",
            "bint",
            "birdlock",
            "bitch",
            "bitch tit",
            "bitch*",
            "bitchass",
            "bitched",
            "bitcher",
            "bitchers",
            "bitches",
            "bitchin",
            "bitching",
            "bitchtits",
            "bitchy",
            "black cock",
            "blonde action",
            "blonde on blonde action",
            "bloodclaat",
            "bloody",
            "bloody hell",
            "blow job",
            "blow me",
            "blow mud",
            "blow your load",
            "blowjob",
            "blowjobs",
            "blue waffle",
            "blumpkin",
            "bod",
            "bodily",
            "boffing",
            "boink",
            "boiolas",
            "bollock",
            "bollock*",
            "bollocks",
            "bollok",
            "bollox",
            "bondage",
            "boned",
            "boner",
            "boners",
            "bong",
            "boob",
            "boobies",
            "boobs",
            "booby",
            "booger",
            "bookie",
            "boong",
            "booobs",
            "boooobs",
            "booooobs",
            "booooooobs",
            "bootee",
            "bootie",
            "booty",
            "booty call",
            "booze",
            "boozer",
            "boozy",
            "bosom",
            "bosomy",
            "breasts",
            "Breeder",
            "brotherfucker",
            "brown showers",
            "brunette action",
            "buceta",
            "bugger",
            "bukkake",
            "bull shit",
            "bulldyke",
            "bullet vibe",
            "bullshit",
            "bullshits",
            "bullshitted",
            "bullturds",
            "bum",
            "bum boy",
            "bumblefuck",
            "bumclat",
            "bummer",
            "buncombe",
            "bung",
            "bung hole",
            "bunghole",
            "bunny fucker",
            "bust a load",
            "busty",
            "butt",
            "butt fuck",
            "butt plug",
            "buttcheeks",
            "buttfuck",
            "buttfucka",
            "buttfucker",
            "butthole",
            "buttmuch",
            "buttmunch",
            "butt-pirate",
            "buttplug",
            "buttwipe",
            "c.0.c.k",
            "c.o.c.k.",
            "c.u.n.t",
            "c0ck",
            "c-0-c-k",
            "c0cks",
            "c0cksucker",
            "c0k",
            "cabron",
            "caca",
            "cacafuego",
            "cahone",
            "camel toe",
            "cameltoe",
            "camgirl",
            "camslut",
            "camwhore",
            "carpet muncher",
            "carpetmuncher",
            "cawk",
            "cawks",
            "cazzo",
            "cervix",
            "chesticle",
            "chi-chi man",
            "chick with a dick",
            "child-fucker",
            "chinc",
            "chincs",
            "chink",
            "chinky",
            "choad",
            "choade",
            "choc ice",
            "chocolate rosebuds",
            "chode",
            "chodes",
            "chota bags",
            "chraa",
            "chuj",
            "cipa",
            "circlejerk",
            "cl1t",
            "cleveland steamer",
            "climax",
            "clit",
            "clit licker",
            "clitface",
            "clitfuck",
            "clitoris",
            "clitorus",
            "clits",
            "clitty",
            "clitty litter",
            "clover clamps",
            "clunge",
            "clusterfuck",
            "cnts",
            "cntz",
            "cnut",
            "cocain",
            "cocaine",
            "coccydynia",
            "cock",
            "c-o-c-k",
            "cock pocket",
            "cock snot",
            "cock sucker",
            "Cock*",
            "cockass",
            "cockbite",
            "cockblock",
            "cockburger",
            "cockeye",
            "cockface",
            "cockfucker",
            "cockhead",
            "cock-head",
            "cockholster",
            "cockjockey",
            "cockknocker",
            "cockknoker",
            "Cocklump",
            "cockmaster",
            "cockmongler",
            "cockmongruel",
            "cockmonkey",
            "cockmunch",
            "cockmuncher",
            "cocknose",
            "cocknugget",
            "cocks",
            "cockshit",
            "cocksmith",
            "cocksmoke",
            "cocksmoker",
            "cocksniffer",
            "cocksuck",
            "cocksucked",
            "cocksucker",
            "cock-sucker",
            "cocksuckers",
            "cocksucking",
            "cocksucks",
            "cocksuka",
            "cocksukka",
            "cockwaffle",
            "coffin dodger",
            "coital",
            "cok",
            "cokmuncher",
            "coksucka",
            "commie",
            "condom",
            "coochie",
            "coochy",
            "coon",
            "coonnass",
            "coons",
            "cooter",
            "cop some wood",
            "coprolagnia",
            "coprophilia",
            "corksucker",
            "cornhole",
            "corp whore",
            "corpulent",
            "cox",
            "crabs",
            "crack",
            "cracker",
            "crackwhore",
            "crap",
            "crappy",
            "creampie",
            "cretin",
            "crikey",
            "cripple",
            "crotte",
            "cum",
            "cum chugger",
            "cum dumpster",
            "cum freak",
            "cum guzzler",
            "cumbubble",
            "cumdump",
            "cumdumpster",
            "cumguzzler",
            "cumjockey",
            "cummer",
            "cummin",
            "cumming",
            "cums",
            "cumshot",
            "cumshots",
            "cumslut",
            "cumstain",
            "cumtart",
            "cunilingus",
            "cunillingus",
            "cunnie",
            "cunnilingus",
            "cunny",
            "cunt",
            "c-u-n-t",
            "cunt hair",
            "cunt*",
            "cuntass",
            "cuntbag",
            "cuntface",
            "cunthole",
            "cunthunter",
            "cuntlick",
            "cuntlicker",
            "cuntlicking",
            "cuntrag",
            "cunts",
            "cuntsicle",
            "cuntslut",
            "cunt-struck",
            "cuntz",
            "cus",
            "cut rope",
            "cyalis",
            "cyberfuc",
            "cyberfuck",
            "cyberfucked",
            "cyberfucker",
            "cyberfuckers",
            "cyberfucking",
            "d!ck",
            "d!cks",
            "d0ng",
            "d0uch3",
            "d0uche",
            "d1ck",
            "d1ld0",
            "d1ldo",
            "d4mn",
            "dago",
            "dagos",
            "dammit",
            "damn",
            "damned",
            "damnit",
            "darkie",
            "darn",
            "date rape",
            "daterape",
            "dawgie-style",
            "daygo",
            "deep throat",
            "deepthroat",
            "deggo",
            "dego",
            "dendrophilia",
            "dick",
            "dick head",
            "dick hole",
            "dick shy",
            "dick*",
            "dickbag",
            "dickbeaters",
            "dickdipper",
            "dickface",
            "dickflipper",
            "dickfuck",
            "dickfucker",
            "dickhead",
            "dickheads",
            "dickhole",
            "dickish",
            "dick-ish",
            "dickjuice",
            "dickmilk",
            "dickmonger",
            "dickripper",
            "dicks",
            "dicksipper",
            "dickslap",
            "dick-sneeze",
            "dicksucker",
            "dicksucking",
            "dicktickler",
            "dickwad",
            "dickweasel",
            "dickweed",
            "dickwhipper",
            "dickwod",
            "dickzipper",
            "diddle",
            "dike",
            "dike*",
            "dild0",
            "dild0s",
            "dildo",
            "dildos",
            "diligaf",
            "dilld0",
            "dilld0s",
            "dillweed",
            "dimwit",
            "dingle",
            "dingleberries",
            "dingleberry",
            "dink",
            "dinks",
            "dipship",
            "dipshit",
            "dirsa",
            "dirty",
            "dirty pillows",
            "dirty sanchez",
            "div",
            "dlck",
            "dog style",
            "dog-fucker",
            "doggie style",
            "doggiestyle",
            "doggie-style",
            "doggin",
            "dogging",
            "doggy style",
            "doggystyle",
            "doggy-style",
            "dolcett",
            "domination",
            "dominatricks",
            "dominatrics",
            "dominatrix",
            "dommes",
            "dong",
            "donkey punch",
            "donkeypunch",
            "donkeyribber",
            "doochbag",
            "doofus",
            "dookie",
            "doosh",
            "dopey",
            "double dong",
            "double penetration",
            "Doublelift",
            "douch3",
            "douche",
            "douchebag",
            "douchebags",
            "douche-fag",
            "douchewaffle",
            "douchey",
            "dp action",
            "drunk",
            "dry hump",
            "duche",
            "dumass",
            "dumb ass",
            "dumbass",
            "dumbasses",
            "Dumbcunt",
            "dumbfuck",
            "dumbshit",
            "dummy",
            "dumshit",
            "dupa",
            "dvda",
            "dyke",
            "dykes",
            "dziwka",
            "eat a dick",
            "eat hair pie",
            "eat my ass",
            "ecchi",
            "ejackulate",
            "ejaculate",
            "ejaculated",
            "ejaculates",
            "ejaculating",
            "ejaculatings",
            "ejaculation",
            "ejakulate",
            "Ekrem*",
            "Ekto",
            "enculer",
            "enema",
            "erect",
            "erection",
            "erotic",
            "erotism",
            "escort",
            "essohbee",
            "eunuch",
            "extacy",
            "extasy",
            "f u c k",
            "f u c k e r",
            "f.u.c.k",
            "f_u_c_k",
            "f4nny",
            "facial",
            "fack",
            "faen",
            "fag",
            "fag*",
            "fag1t",
            "fagbag",
            "faget",
            "fagfucker",
            "fagg",
            "fagg0t",
            "fagg1t",
            "fagged",
            "fagging",
            "faggit",
            "faggitt",
            "faggot",
            "faggotcock",
            "faggots",
            "faggs",
            "fagit",
            "fagot",
            "fagots",
            "fags",
            "fagtard",
            "fagz",
            "faig",
            "faigs",
            "faigt",
            "fanculo",
            "fanny",
            "fannybandit",
            "fannyflaps",
            "fannyfucker",
            "fanyy",
            "fart",
            "fartknocker",
            "fatass",
            "fcuk",
            "fcuker",
            "fcuking",
            "fecal",
            "feces",
            "feck",
            "fecker",
            "feg",
            "feist",
            "felch",
            "felcher",
            "felching",
            "fellate",
            "fellatio",
            "feltch",
            "feltcher",
            "female squirting",
            "femdom",
            "fenian",
            "fice",
            "ficken",
            "figging",
            "fingerbang",
            "fingerfuck",
            "fingerfucked",
            "fingerfucker",
            "fingerfuckers",
            "fingerfucking",
            "fingerfucks",
            "fingering",
            "fist fuck",
            "fisted",
            "fistfuck",
            "fistfucked",
            "fistfucker",
            "fistfuckers",
            "fistfucking",
            "fistfuckings",
            "fistfucks",
            "fisting",
            "fisty",
            "fitt*",
            "flamer",
            "flange",
            "flaps",
            "fleshflute",
            "Flikker",
            "flipping the bird",
            "flog the log",
            "floozy",
            "foad",
            "foah",
            "fondle",
            "foobar",
            "fook",
            "fooker",
            "foot fetish",
            "footjob",
            "foreskin",
            "Fotze",
            "freex",
            "frenchify",
            "frigg",
            "frigga",
            "frotting",
            "fubar",
            "fuc",
            "fuck",
            "f-u-c-k",
            "fuck buttons",
            "fuck hole",
            "Fuck off",
            "fuck puppet",
            "fuck trophy",
            "fuck yo mama",
            "fuck you",
            "fucka",
            "fuckass",
            "fuck-ass",
            "fuckbag",
            "fuck-bitch",
            "fuckboy",
            "fuckbrain",
            "fuckbutt",
            "fuckbutter",
            "fucked",
            "fuckedup",
            "fucker",
            "fuckers",
            "fuckersucker",
            "fuckface",
            "fuckhead",
            "fuckheads",
            "fuckhole",
            "fuckin",
            "fucking",
            "fuckings",
            "fuckingshitmotherfucker",
            "fuckme",
            "fuckmeat",
            "fucknugget",
            "fucknut",
            "fucknutt",
            "fuckoff",
            "fucks",
            "fuckstick",
            "fucktard",
            "fuck-tard",
            "fucktards",
            "fucktart",
            "fucktoy",
            "fucktwat",
            "fuckup",
            "fuckwad",
            "fuckwhit",
            "fuckwit",
            "fuckwitt",
            "fudge packer",
            "fudgepacker",
            "fudge-packer",
            "fuk",
            "fuk*",
            "Fukah",
            "Fuken",
            "fuker",
            "Fukin",
            "Fukk",
            "Fukkah",
            "Fukken",
            "Fukker",
            "fukkers",
            "fukkin",
            "fuks",
            "fukwhit",
            "fukwit",
            "fuq",
            "futanari",
            "futkretzn",
            "fux",
            "fux0r",
            "fvck",
            "fxck",
            "g00k",
            "gae",
            "gai",
            "gang bang",
            "gangbang",
            "gang-bang",
            "gangbanged",
            "gangbangs",
            "ganja",
            "gash",
            "gassy ass",
            "gay",
            "gay sex",
            "gayass",
            "gaybob",
            "gaydo",
            "gayfuck",
            "gayfuckist",
            "gaylord",
            "gays",
            "gaysex",
            "gaytard",
            "gaywad",
            "gender bender",
            "genitals",
            "gey",
            "gfy",
            "ghay",
            "ghey",
            "giant cock",
            "gigolo",
            "ginger",
            "gippo",
            "girl on",
            "girl on top",
            "girls gone wild",
            "git",
            "glans",
            "goatcx",
            "goatse",
            "god",
            "god damn",
            "godamn",
            "godamnit",
            "goddam",
            "god-dam",
            "goddammit",
            "goddamn",
            "goddamned",
            "god-damned",
            "goddamnit",
            "godsdamn",
            "gokkun",
            "golden shower",
            "goldenshower",
            "golliwog",
            "gonad",
            "gonads",
            "goo girl",
            "gooch",
            "goodpoop",
            "gook",
            "gooks",
            "goregasm",
            "gringo",
            "grope",
            "group sex",
            "gspot",
            "g-spot",
            "gtfo",
            "guido",
            "guiena",
            "guro",
            "h00r",
            "h0ar",
            "h0m0",
            "h0mo",
            "h0r",
            "h0re",
            "h4x0r",
            "ham flap",
            "hand job",
            "handjob",
            "hard core",
            "hard on",
            "hardcore",
            "hardcoresex",
            "he11",
            "hebe",
            "heeb",
            "hell",
            "hells",
            "helvete",
            "hemp",
            "hentai",
            "heroin",
            "herp",
            "herpes",
            "herpy",
            "heshe",
            "he-she",
            "hircismus",
            "hitler",
            "hiv",
            "ho",
            "hoar",
            "hoare",
            "hobag",
            "hoe",
            "hoer",
            "hoer*",
            "holy shit",
            "hom0",
            "homey",
            "homo",
            "homodumbshit",
            "homoerotic",
            "homoey",
            "honkey",
            "honky",
            "hooch",
            "hookah",
            "hooker",
            "hoor",
            "hoore",
            "hootch",
            "hooter",
            "hooters",
            "hore",
            "horniest",
            "horny",
            "hot carl",
            "hot chick",
            "hotsex",
            "how to kill",
            "how to murdep",
            "how to murder",
            "Huevon",
            "huge fat",
            "hui",
            "hump",
            "humped",
            "humping",
            "hun",
            "hussy",
            "hymen",
            "iap",
            "iberian slap",
            "inbred",
            "incest",
            "injun",
            "intercourse",
            "jack off",
            "jackass",
            "jackasses",
            "jackhole",
            "jackoff",
            "jack-off",
            "jaggi",
            "jagoff",
            "jail bait",
            "jailbait",
            "jap",
            "japs",
            "jelly donut",
            "jerk",
            "jerk off",
            "jerk0ff",
            "jerkass",
            "jerked",
            "jerkoff",
            "jerk-off",
            "jigaboo",
            "jiggaboo",
            "jiggerboo",
            "jisim",
            "jism",
            "jiss",
            "jiz",
            "jizm",
            "jizz",
            "jizzed",
            "jock",
            "juggs",
            "jungle bunny",
            "junglebunny",
            "junkie",
            "junky",
            "kafir",
            "kanker*",
            "kawk",
            "kike",
            "kikes",
            "kill",
            "kinbaku",
            "kinkster",
            "kinky",
            "klan",
            "klootzak",
            "knob",
            "knob end",
            "knobbing",
            "knobead",
            "knobed",
            "knobend",
            "knobhead",
            "knobjocky",
            "knobjokey",
            "knobs",
            "knobz",
            "knulle",
            "kock",
            "kondum",
            "kondums",
            "kooch",
            "kooches",
            "kootch",
            "kraut",
            "kuk",
            "kuksuger",
            "kum",
            "kummer",
            "kumming",
            "kums",
            "kunilingus",
            "kunja",
            "kunt",
            "kunts",
            "kuntz",
            "Kurac",
            "kurwa",
            "kusi*",
            "kwif",
            "kyke",
            "kyrpa*",
            "l3i+ch",
            "l3itch",
            "labia",
            "lameass",
            "lardass",
            "leather restraint",
            "leather straight jacket",
            "lech",
            "lemon party",
            "LEN",
            "leper",
            "lesbian",
            "lesbians",
            "lesbo",
            "lesbos",
            "lez",
            "lezza/lesbo",
            "Lezzian",
            "lezzie",
            "Lipshits",
            "Lipshitz",
            "lmao",
            "lmfao",
            "loin",
            "loins",
            "lolita",
            "looney",
            "lovemaking",
            "lube",
            "lust",
            "lusting",
            "lusty",
            "m0f0",
            "m0fo",
            "m45terbate",
            "ma5terb8",
            "ma5terbate",
            "mafugly",
            "make me come",
            "male squirting",
            "mamhoon",
            "mams",
            "masochist",
            "masokist",
            "massa",
            "massterbait",
            "masstrbait",
            "masstrbate",
            "masterb8",
            "masterbaiter",
            "masterbat*",
            "masterbat3",
            "masterbate",
            "master-bate",
            "masterbates",
            "masterbating",
            "masterbation",
            "masterbations",
            "masturbat*",
            "masturbate",
            "masturbating",
            "masturbation",
            "maxi",
            "mcfagget",
            "menage a trois",
            "menses",
            "menstruate",
            "menstruation",
            "merd*",
            "meth",
            "m-fucking",
            "mibun",
            "mick",
            "microphallus",
            "middle finger",
            "midget",
            "milf",
            "minge",
            "minger",
            "missionary position",
            "mof0",
            "mofo",
            "mo-fo",
            "molest",
            "mong",
            "monkleigh",
            "moo moo foo foo",
            "moolie",
            "moron",
            "Motha Fucker",
            "Motha Fuker",
            "Motha Fukkah",
            "Motha Fukker",
            "mothafuck",
            "mothafucka",
            "mothafuckas",
            "mothafuckaz",
            "mothafucked",
            "mothafucker",
            "mothafuckers",
            "mothafuckin",
            "mothafucking",
            "mothafuckings",
            "mothafucks",
            "mother fucker",
            "Mother Fukah",
            "Mother Fuker",
            "Mother Fukkah",
            "Mother Fukker",
            "motherfuck",
            "motherfucka",
            "motherfucked",
            "motherfucker",
            "mother-fucker",
            "motherfuckers",
            "motherfuckin",
            "motherfucking",
            "motherfuckings",
            "motherfuckka",
            "motherfucks",
            "mouliewop",
            "mound of venus",
            "mr hands",
            "muff",
            "muff diver",
            "muff puff",
            "muffdiver",
            "muffdiving",
            "muie",
            "mulkku",
            "munging",
            "munter",
            "murder",
            "muschi",
            "mutha",
            "Mutha Fucker",
            "Mutha Fukah",
            "Mutha Fuker",
            "Mutha Fukkah",
            "Mutha Fukker",
            "muthafecker",
            "muthafuckker",
            "muther",
            "mutherfucker",
            "n1gga",
            "n1gger",
            "n1gr",
            "naked",
            "nambla",
            "napalm",
            "nappy",
            "nastt",
            "nawashi",
            "nazi",
            "nazis",
            "nazism",
            "need the dick",
            "negro",
            "neonazi",
            "nepesaurio",
            "nig nog",
            "nigaboo",
            "nigg3r",
            "nigg4h",
            "nigga",
            "niggah",
            "niggas",
            "niggaz",
            "nigger",
            "nigger*",
            "nigger;",
            "niggers",
            "niggle",
            "niglet",
            "nig-nog",
            "nigur;",
            "niiger;",
            "niigr;",
            "nimphomania",
            "nimrod",
            "ninny",
            "ninnyhammer",
            "nipple",
            "nipples",
            "nob",
            "nob jokey",
            "nobhead",
            "nobjocky",
            "nobjokey",
            "nonce",
            "nsfw images",
            "nude",
            "nudity",
            "numbnuts",
            "nut butter",
            "nut sack",
            "nutsack",
            "nutter",
            "nympho",
            "nymphomania",
            "octopussy",
            "old bag",
            "omg",
            "omorashi",
            "one cup two girls",
            "one guy one jar",
            "opiate",
            "opium",
            "orafis",
            "orally",
            "organ",
            "orgasim",
            "orgasim;",
            "orgasims",
            "orgasm",
            "orgasmic",
            "orgasms",
            "orgasum",
            "orgies",
            "orgy",
            "oriface",
            "orifice",
            "orifiss",
            "orospu",
            "ovary",
            "ovum",
            "ovums",
            "p.u.s.s.y.",
            "p0rn",
            "packi",
            "packie",
            "packy",
            "paedophile",
            "paki",
            "pakie",
            "paky",
            "panooch",
            "pansy",
            "pantie",
            "panties",
            "panty",
            "paska*",
            "pawn",
            "pcp",
            "pecker",
            "peckerhead",
            "pedo",
            "pedobear",
            "pedophile",
            "pedophilia",
            "pedophiliac",
            "pee",
            "peeenus",
            "peeenusss",
            "peenus",
            "peepee",
            "pegging",
            "peinus",
            "pen1s",
            "penas",
            "penetrate",
            "penetration",
            "penial",
            "penile",
            "penis",
            "penisbanger",
            "penis-breath",
            "penisfucker",
            "penispuffer",
            "penus",
            "penuus",
            "perse",
            "perversion",
            "phallic",
            "phone sex",
            "phonesex",
            "Phuc",
            "Phuck",
            "phuk",
            "phuked",
            "Phuker",
            "phuking",
            "phukked",
            "Phukker",
            "phukking",
            "phuks",
            "phuq",
            "picka",
            "piece of shit",
            "pierdol*",
            "pigfucker",
            "pikey",
            "pillowbiter",
            "pillu*",
            "pimmel",
            "pimp",
            "pimpis",
            "pinko",
            "piss",
            "piss off",
            "piss pig",
            "piss*",
            "pissed",
            "pissed off",
            "pisser",
            "pissers",
            "pisses",
            "pissflaps",
            "pissin",
            "pissing",
            "pissoff",
            "piss-off",
            "pisspig",
            "pizda",
            "playboy",
            "pleasure chest",
            "pms",
            "polac",
            "polack",
            "polak",
            "pole smoker",
            "polesmoker",
            "pollock",
            "ponyplay",
            "poof",
            "poon",
            "poonani",
            "poonany",
            "poontang",
            "poontsee",
            "poop",
            "poop chute",
            "poopchute",
            "Poopuncher",
            "porch monkey",
            "porchmonkey",
            "porn",
            "porno",
            "pornography",
            "pornos",
            "pot",
            "potty",
            "pr0n",
            "pr1c",
            "pr1ck",
            "pr1k",
            "preteen",
            "prick",
            "pricks",
            "prickteaser",
            "prig",
            "prince albert piercing",
            "prod",
            "pron",
            "prostitute",
            "prude",
            "psycho",
            "pthc",
            "pube",
            "pubes",
            "pubic",
            "pubis",
            "pula",
            "pule",
            "punani",
            "punanny",
            "punany",
            "punkass",
            "punky",
            "punta",
            "puss",
            "pusse",
            "pussee",
            "pussi",
            "pussies",
            "pussy",
            "pussy fart",
            "pussy palace",
            "pussylicking",
            "pussypounder",
            "pussys",
            "pust",
            "puta",
            "puto",
            "puuke",
            "puuker",
            "qahbeh",
            "queaf",
            "queef",
            "queef*",
            "queer",
            "queerbait",
            "queerhole",
            "queero",
            "queers",
            "queerz",
            "quicky",
            "quim",
            "qweers",
            "qweerz",
            "qweir",
            "racy",
            "raghead",
            "raging boner",
            "rape",
            "raped",
            "raper",
            "rapey",
            "raping",
            "rapist",
            "raunch",
            "rautenberg",
            "recktum",
            "rectal",
            "rectum",
            "rectus",
            "reefer",
            "reetard",
            "reich",
            "renob",
            "retard",
            "retarded",
            "reverse cowgirl",
            "revue",
            "rimjaw",
            "rimjob",
            "rimming",
            "ritard",
            "rosy palm",
            "rosy palm and her 5 sisters",
            "rtard",
            "r-tard",
            "rubbish",
            "rum",
            "rump",
            "rumprammer",
            "ruski",
            "rusty trombone",
            "s hit",
            "s&m",
            "s.h.i.t.",
            "s.o.b.",
            "s_h_i_t",
            "s0b",
            "sadism",
            "sadist",
            "sambo",
            "sand nigger",
            "sandbar",
            "Sandler",
            "sandnigger",
            "sanger",
            "santorum",
            "sausage queen",
            "scag",
            "scank",
            "scantily",
            "scat",
            "schaffer",
            "scheiss*",
            "schizo",
            "schlampe",
            "schlong",
            "schmuck",
            "scissoring",
            "screw",
            "screwed",
            "screwing",
            "scroat",
            "scrog",
            "scrot",
            "scrote",
            "scrotum",
            "scrud",
            "scum",
            "seaman",
            "seamen",
            "seduce",
            "seks",
            "semen",
            "sex",
            "sexo",
            "sexual",
            "sexy",
            "sh!+",
            "sh!t",
            "sh!t*",
            "sh1t",
            "s-h-1-t",
            "sh1ter",
            "sh1ts",
            "sh1tter",
            "sh1tz",
            "shag",
            "shagger",
            "shaggin",
            "shagging",
            "shamedame",
            "sharmuta",
            "sharmute",
            "shaved beaver",
            "shaved pussy",
            "shemale",
            "shi+",
            "shibari",
            "shipal",
            "shirt lifter",
            "shit",
            "s-h-i-t",
            "shit ass",
            "shit fucker",
            "shitass",
            "shitbag",
            "shitbagger",
            "shitblimp",
            "shitbrains",
            "shitbreath",
            "shitcanned",
            "shitcunt",
            "shitdick",
            "shite",
            "shiteater",
            "shited",
            "shitey",
            "shitface",
            "shitfaced",
            "shitfuck",
            "shitfull",
            "shithead",
            "shitheads",
            "shithole",
            "shithouse",
            "shiting",
            "shitings",
            "shits",
            "shitspitter",
            "shitstain",
            "shitt",
            "shitted",
            "shitter",
            "shitters",
            "shittier",
            "shittiest",
            "shitting",
            "shittings",
            "shitty",
            "Shity",
            "shitz",
            "shiz",
            "shiznit",
            "shota",
            "shrimping",
            "Shyt",
            "Shyte",
            "Shytty",
            "Shyty",
            "sissy",
            "skag",
            "skanck",
            "skank",
            "skankee",
            "skankey",
            "skanks",
            "Skanky",
            "skeet",
            "skribz",
            "skullfuck",
            "skurwysyn",
            "slag",
            "slanteye",
            "slave",
            "sleaze",
            "sleazy",
            "slope",
            "slut",
            "slut bucket",
            "slutbag",
            "slutdumper",
            "slutkiss",
            "sluts",
            "Slutty",
            "slutz",
            "smartass",
            "smartasses",
            "smeg",
            "smegma",
            "smut",
            "smutty",
            "snatch",
            "sniper",
            "snowballing",
            "snuff",
            "s-o-b",
            "sod off",
            "sodom",
            "sodomize",
            "sodomy",
            "son of a bitch",
            "son of a motherless goat",
            "son of a whore",
            "son-of-a-bitch",
            "souse",
            "soused",
            "spac",
            "spade",
            "sperm",
            "sphencter",
            "spic",
            "spick",
            "spierdalaj",
            "spik",
            "spiks",
            "splooge",
            "splooge moose",
            "spooge",
            "spook",
            "spread legs",
            "spunk",
            "stfu",
            "stiffy",
            "stoned",
            "strap on",
            "strapon",
            "strappado",
            "strip",
            "strip club",
            "stroke",
            "stupid",
            "style doggy",
            "suck",
            "suckass",
            "sucked",
            "sucking",
            "sucks",
            "suicide girls",
            "suka",
            "sultry women",
            "sumofabiatch",
            "swastika",
            "swinger",
            "t1t",
            "t1tt1e5",
            "t1tties",
            "taff",
            "taig",
            "tainted love",
            "taking the piss",
            "tampon",
            "tard",
            "tart",
            "taste my",
            "tawdry",
            "tea bagging",
            "teabagging",
            "teat",
            "teets",
            "teez",
            "teste",
            "testee",
            "testes",
            "testical",
            "testicle",
            "testicle*",
            "testis",
            "threesome",
            "throating",
            "thrust",
            "thug",
            "thundercunt",
            "tied up",
            "tight white",
            "tinkle",
            "tit",
            "tit wank",
            "titfuck",
            "titi",
            "tities",
            "tits",
            "titt",
            "titt*",
            "tittie5",
            "tittiefucker",
            "titties",
            "titty",
            "tittyfuck",
            "tittyfucker",
            "tittywank",
            "titwank",
            "toke",
            "tongue in a",
            "toots",
            "topless",
            "tosser",
            "towelhead",
            "tramp",
            "tranny",
            "transsexual",
            "trashy",
            "tribadism",
            "trumped",
            "tub girl",
            "tubgirl",
            "turd",
            "tush",
            "tushy",
            "tw4t",
            "twat",
            "twathead",
            "twatlips",
            "twats",
            "twatty",
            "twatwaffle",
            "twink",
            "twinkie",
            "two fingers",
            "two fingers with tongue",
            "two girls one cup",
            "twunt",
            "twunter",
            "ugly",
            "unclefucker",
            "undies",
            "undressing",
            "unwed",
            "upskirt",
            "urethra play",
            "urinal",
            "urine",
            "urophilia",
            "uterus",
            "uzi",
            "v14gra",
            "v1gra",
            "va1jina",
            "vag",
            "vag1na",
            "vagiina",
            "vagina",
            "vaj1na",
            "vajayjay",
            "vajina",
            "va-j-j",
            "valium",
            "venus mound",
            "veqtable",
            "viagra",
            "vibrator",
            "violet wand",
            "virgin",
            "vittu",
            "vixen",
            "vjayjay",
            "vodka",
            "vomit",
            "vorarephilia",
            "voyeur",
            "vulgar",
            "vullva",
            "vulva",
            "w00se",
            "w0p",
            "wad",
            "wang",
            "wank",
            "wank*",
            "wanker",
            "wankjob",
            "wanky",
            "wazoo",
            "wedgie",
            "weed",
            "weenie",
            "weewee",
            "weiner",
            "weirdo",
            "wench",
            "wet dream",
            "wetback",
            "wetback*",
            "wh00r",
            "wh0re",
            "wh0reface",
            "white power",
            "whiz",
            "whoar",
            "whoralicious",
            "whore",
            "whorealicious",
            "whorebag",
            "whored",
            "whoreface",
            "whorehopper",
            "whorehouse",
            "whores",
            "whoring",
            "wichser",
            "wigger",
            "willies",
            "willy",
            "window licker",
            "wiseass",
            "wiseasses",
            "wog",
            "womb",
            "wop",
            "wop*",
            "wrapping men",
            "wrinkled starfish",
            "wtf",
            "xrated",
            "x-rated",
            "xx",
            "xxx",
            "yaoi",
            "yeasty",
            "yed",
            "yellow showers",
            "yid",
            "yiffy",
            "yobbo",
            "zabourah",
            "zibbi",
            "zoophilia",
            "zubb"
        };

        internal static Lazy<ISet<Regex>> Expressions = new Lazy<ISet<Regex>>(() => EvaluateExpressions());

        static ISet<Regex> EvaluateExpressions()
        {
            var set = new HashSet<Regex>();
            foreach (var wordOrPhrase in
                WordsAndPhrases.Select(term => Regex.Replace(term, @"/(\W)/g", "$1")))
            {
                set.Add(new Regex($"\\b{wordOrPhrase}\\b", RegexOptions.IgnoreCase));
            }

            return set;
        }

        #endregion
    }
}